export const MAGIC_VALUES = {
  HABITS: {
    SUCCESS_RATE: 0.82,
    CONSISTENCY_INCREASE: 0.18,
  },
  SLEEP: {
    CONSISTENCY_PERCENT: 0.85,
    EXTRA_HOURS_PER_WEEK: 1.2,
    DEFAULT_SCORE: 0.71,
  },
  DASHBOARD: {
    OVERALL_SCORE: 0.75,
    SOCIAL_SCORE: 0.4,
    DEFAULT_BAR_VALUE: 0.2,
    MAX_BAR_VALUE: 1.0,
  },
  GOALS: {
    FOCUS_INCREASE_PERCENT: 0.22,
    BADGE_THRESHOLD: 0.5,
  },
} as const;
